name = "plex-services"
main = "src/index.ts"
compatibility_date = "2023-10-16"
workers_dev = false

services = [
  { binding = "SEND_EMAIL", service = "send-email"}
]

routes = [
	{ pattern = "api.gamolsky.net", custom_domain = true },
]

[vars]
SENDGRID_TO_EMAIL = "plexrequest@gamolsky.net"
NOTION_PLEX_REQUEST_DATABASE_ID = "e5296ba6f21845cf85201c96e50bddb9"

[env.local]
vars = { WORKER_ENV = "local", SENDGRID_TO_EMAIL = "plexrequest@gamolsky.net", NOTION_PLEX_REQUEST_DATABASE_ID = "e5296ba6f21845cf85201c96e50bddb9" }
services = [
  { binding = "SEND_EMAIL", service = "send-email"}
]


